### ISSUE TITLE
Problem with gene families containing 2 sequences ?

### ISSUE THREAD

**Issue by BiodivGenomic** [arzwa/wgd#9] opened 2019-02-04 16:29 UTC
Hi,
I would like to know if the smallest multi-copies families can be an issue for wgd... I can imagine phyml will maybe run into trouble building a tree with only 2 sequences, but is wgd dealing with these families ?
I ask this question because analyses seems to stall using phyml for the second step (ksd), each time at a gene family containing 2 members... I would like to exclude this issue before troubleshooting more :-)

**Comment by arzwa** [comment] 2019-02-04 16:48
Hi, 

`wgd ksd` should take into account this issue. If you run wgd with the `-v debug` flag you'll see the following for a family with only two members:

```
2019-02-04 17:38:12: DEBUG	PhyML breaks with only two genes, do ALC instead.
2019-02-04 17:38:12: DEBUG	Distance will be in Ks units!
2019-02-04 17:38:12: DEBUG	Performing average linkage clustering on Ks values.
```

In other words, analyses should not stall when encountering only two family members.

Here is an example data set to show a MWE, `sample.mcl`:
```
AT5G24210.1 AT5G24230.3 AT4G10955.1
AT1G01080.3 AT5G53680.1
AT5G13590.1 AT5G13590.2
AT1G02610.1
```
make sure they are tab separated (`sed -i 's/ /\t/g sample.mcl` is your friend after copying)

`sample.fasta`:

```
>AT1G01080.3
ATGGCGGCCTCCTGCTTCGCAATTCCCTTATCTTCTTCTTCTCGATCGTCTCACAATGCAATTCCCAAATACAAAACCCTAATCTCTTCTTCTTCTTACTCTTACTTAGAATCTCTGAAACTTCAATTCTCTTCTTCCAATTCTTTTCATCACTCTTCTCTTTCTCGTCCCTTTGTAGCTCAACCACTTCAAATCAAGGTCTCTTCTTCAGAATTATCAGTTCTCGATGAAGAAAAAGAAGAAGAAGTAGTTAAAGGAGAAGCAGAACCCAATAAAGATAGTGTCGTCTCCAAAGCAGAACCAGTAAAGAAACCGAGACCTTGCGAGCTCTACGTGTGTAATATCCCTAGAAGCTACGACATTGCTCAGCTTCTTGACATGTTTCAGCCTTTTGGAACTGTAATCTCTGTAGAGGTATCGCGAAATCCTCAGACGGGAGAGAGCCGTGGAAGCGGGTACGTGACAATGGGTTCTATAAACTCTGCCAAAATCGCCATTGCTTCTCTTGATGGAACAGAAGTAGGTGGTCGGGAAATGCGGGTTAGGTACTCTGTTGACATGAATCCAGGAACAAGAAGAAACCCTGAAGTCTTGAACTCAACTCCAAAGAAGATTCTGATGTACGAAAGCCAACACAAGGTCTATGTCGGAAATCTCCCTTGGTTCACACAGCCTGATGGTTTGAGAAACCACTTTAGCAAGTTTGGCACAATCGTAAGCACGAGAGTGTTACATGATCGTAAGACCGGGAGAAACAGAGTCTTTGCCTTTCTTTCTTTTACAAGCGGTGAAGAACGTGATGCGGCTTTATCATTCAATGGAACAGTTAAGTTCGTTATCCATAAAAAGAATCTTGCTTGA
>AT1G02610.1
ATGGGAGATGTAGTTTTGTTCATAGATGAAACATATTTGAAATCGAGTTTTAATCGCTGTAGAATCTGTCACGAAGAAGAAGCTGAGAGCTACTTTGAAGCTCCTTGTTCTTGTTCAGGAACCATCAAGTTCGCTCACAGAGATTGCATACAACGATGGTGTGATGAGAAAGGAAACACAATTTGTGAAATTTGTCTCCAGGAGTATAAACCTGGATACACCACAACTTCAAAACCATCTCGATTTATTGAAACAGCAGTCACAATCAGAGATAATTTACACATAATGAGAAGAGAAAATGGAAGAAGAAGAAGAAATAGAAGATTAGTGAATAGAGAAGAATCAGATTTTCAAGAATGCAACTCTGGTGTTGATAGAGGCGCCTCTTGTTGTAGATACTTGGCTCTCATTTTTTCGGTTATTTTGTTGATAAAGCATGCATTTGATGCGGTTTATGGAACTGAAGAGTATCCCTATACAATATTCACGGTCTTAACATTGAAGGCTATAGGCATACTATTACCAATGCTCGTTATCATTCGAACCATCACAGCTATTCAAAGGAGTCTCCGATATCAAATTCTCGAATCAGAAGAAGATACATTGAGCTCTGAAGAAGAAGATCATGGTTTGGAGGAGGAAGAGCAACAACAACATATAGCTTGA
>AT5G24210.1
ATGGGAAACTTAAAAAAATCTACACGCAGTGACGAGTTAAGCCGTTCTGGTCCCCCTCAAATTCCAAATCCTGACTGGAACAATTTGTATCACCGAACCACAGTGGCCTCATGTTTGGTGCAAGGAGTTTACGCAAAGGAAAGAGACAGGGAAAACAACCGAAATGGTTCCGAGTCATTAGCCACACCTTGGTGGAAGAGTTTCAACTTCACTTTAGATGAAAGTGAAATCCTATATGACGCATTTGACGGCTCCATATACGGTGCTGTCTTCCAAAACATGATCAATTATGAGAATACCCCGAACTCGATAGTAGTACCTCCGCGTTACGTGATTGCGTTACGGGGAACTGTCCCAAGTGATGTGAGTGATTGGATACATAACAGCCGTATTGTACTCGAGAAACTCCATGGCGGGGGTAAGCATATGCATGTCATTAGAAAAATCTATTCTTTGGTGGCCAAACACGGAAACACAGCTGTCTGGATCGCTGGACACTCTTTAGGAGCTGGCCTGGCACTACTCGCGGGAAAGGACATGGCCATGTCTGGACTCCCTGTTGAGGCTTACATCTTCAACCCACCTATCTCCTTGATTCCTCTAGAGCAGTGCGGTTACAATCACGAACTTAATTTTGTGTATCGACTCACCAGGGATCTCTTCAAAGCTGGCATAGCCAAAGTCGTAGACCTTGATGAGGGTCAAGAGGGTCCACGATATAAGAACTTAGCTTCTTGGAGACCTCATTTGTTTGTGAACCAATCTGATGTAATATGCTCAGAATATATTGGTTATTTCAATCACGTAGTCACTATGACGGAGGCGGGACTCGGTGAGATTTCGAGGTTGGCTAGTGGATACTCAGTTAGGCGTATGTTATTCGGAGACGGAGAAAATTGGTCCTCGTCTTCTACACCAGATCATCTTCATTTTCTTCCGTCGGCCTTTATGATTGTAAACAAGACTGAAGCGTCGGAGTTTTATAATAAACATGGGATTCATCAATGGTGGAATCATATGCTTAAACAATCTACAACGTTTAGTTCATACTAG
>AT5G53680.1
ATGTCTCACCACCACCAAAACTTCGATACAACATTCACAAAGATATACGTGGGGGGTTTGCCTTGGACAACAAGAAAGGAAGGCTTGATAAACTTCTTCAAACGTTTTGGTGAAATCATCCATGTGAACGTCGTTTGTGATAGAGAAACAGATCGATCACAAGGATATGGCTTCGTCACGTTTAAAGACGCTGAATCTGCAACAAGAGCTTGCAAGGATCCGAATCCGACTATTGAAGGACGAATAACTAATTGCAAACTCGCTTTCGTTGGTGCTAAAGTTAAACCTAACCAATCCCAACCTTCAAATTTGCCTCAATTATTACCTAGGTATGATCCGCAATATAATCCGCGGTATGATCCGATGTCTTACCAACAAAACCGTATGGCTAACAACACCAACAATGGTATTGGCAGCATCCAACTACAAACGTTGTTAACGGAGAATCGAGCAGCTCACAGGCTACGGGAACGCAGCCAGAGTTTCTTTCGACACCGGGATCTTCGCTAA
>AT4G10955.1
ATGATGATTAGTGAAAGAGATGATTTTAGTCTCACTGGACCATTACACTTAACATCTATAGATTGGGCTAATGAACATCATCGACGATCCGTAGCTGGATCTTTGGTTCAAGGAATCTATGTAGCTGAGCGTGACCGTCAGCTACAAAGAGAAGGTCCTGAGTTAGCTTTATCTCCAATATGGTCTGAGTTTTTCCATTTCCGCCTCATTCGTAAGTTTGTCGATGACGCGGATAACTCTATCTTCGGAGGAATCTATGAGTACAAACTGCCGCAACAGCTCTCTCAAACCGTCAAATCAATGGAATTTAGTCCACGTTTTGTGATTGCTTTCAGAGGAACGGTTACAAAAGTGGACTCCATTTCCCGTGACATCGAGCATGACATCCATGTTATTAGAAACGGGCTTCACACGACAACACGGTTTGAGATAGCTATCCAAGCAGTGAGAAACATTGTTGCTTCGGTTGGTGGTTCTAGTGTTTGGCTTGCTGGTCATTCTCTTGGTGCATCTATGGCATTACTTACCGGGAAAACCATCGCTAGAACCGGGTTTTTTCCTGAGTGTTTCGCATTCAATCCGCCGTTTTTGTCTGCCCCTATCGAAAAAATTAAGGATAAGAGGATTAAACATGGGATACGCATTGCAGGCAGTGTGATCACAGCTGGACTTGCTCTAGCCAAAAAAGCCACCCAACACTACAGCCAAAACGACCGTGCATTACCCGCACCTCCTGATCCATTTGAAGCTTTATCCGACTGGTTCCCGCGGCTGTATGTCAACCCTGGTGACCACTTATGCTCAGAGTATGTTGGTTACTTTGAGCACCGAAACAAGATGGAAGAAATCGGGATTGGGTTTGTAGAGCGGGTAGCGACGCAGCACTCGTTGGGCGGTATGCTGTTAGGAGGACAAGAGCCGGTACATCTGATTCCATCTTCGGTTTTGACGGTGAACTTAAGCTCCTCGAGAGATTTCAAACAAGCTCATGGGATTCATCAGTGGTGGAGGGAAGATAACAAGTTTGAGACTAAAGTTTACCAGTACAAATGA
>AT5G13590.1
ATGTCTGGAAGCCAAGAGCCTAGGATCAGACCATCTACATGGAGCTGCAGTGATATTCCAATCAAGAAGAGGAAGTACCTTGTTCAGCCGCAAATGGAAGAAGCTGTCTCCACTCAGATTCCACAACCTAATGAGCAAGGTGATACTAGGAGTGCTCATGCTGACGAAACTCAGAAAATGACTGGTCGAGAACCAACCTCTTCATTACCATCTGTTCCTGTGGGAATTTCTGGTAAAGGGAAGAGCATTGGGAACATAGTTTTTGACCAAACTAGAGTGAAATTTGAGAAGCCAAGTTCTCCAATTCACTCCAGTCCATTGGCAGGCTTTGACATCCCTTCTAGTTCTAACGTACTTGGCAGTTCAATCCATTTTCCTATGGGAAAGCTTCCTGTTGGTGCTGAACATGCTGGTCTTGTTGTCCCCTCAAATCAAACTCGGATGAAAGTAGAAAAAACTGTTCTTAAGACTCATGATATAGTCCGGAAGACAGGTGACAAGGAAACTCTCAGAGGAGAGTGTCAAACAGAAGCATCTTCTGGTGCTAAGACTGTTTCCTTACAGCTAAGTTGTAACACTAAAAACAATTCTCCATATTGGAAGAATGAAGAGCCTACAGAACTGAATTTGTCATTAAGCAAGGGAGTTTGTCCCGCTCATAACACAGATTCTACTTCTACCAAATCTGGCAACAGTGGCCTGAACAGAGAAAATTGGGATTTGAATACTACCATGGATGTTTGGGAAGATGCTCTAGATCGCACAAGTGGTGCATTCTTAAACAGTAACAGAAGTCTTCGTGACATAGAGAGATCAAGTTGTCGTGATACGACTGCTATTACAAAGTCTGTTTCTGAAAGACAGAAGGAAAGTGTAGGATTTAGTTCTCCTAAGGTGACGTTGATGCAGTTTGATAATCATGTTAATCCCACATGCTCACTTAGTCTAGGCCTCAGTTCATATCCTCCTATTGAGAAATCTCCTTCTCTACCAGCTACCACATCAGAGGCAAGAGCTGGGAATGTGTGTTCAGTGAACCTTAGGACTGTGAAGTCAGAAATCATTGAAGAGAGTGTTAGGCAGGCAACAGAGAGTACTCAAGTTTCTCCAATCGGGCTATCTATTAAAGGACTGAAACATGAGGGTATTGGCAGATTCAGCCAAGGAAATAGTCCCTCATTTGGCATTTTGAAGACAGTGGTTCCTATATCAATAAAGGCTGAGCCAAATACCTTCTCTCAATCAGAAGTTTTCAATAGGAAAGATGGAATGTTGAATCATCCCCATACCCCAATAATGCAATCAAATGAGATCCCTGATTTACCTACAAGTTCTACGCCATATCAGAAGGATAAATATTTACCTTGTTCAAATGGTATCAGCAATGCACCAATGCCCTTGAGTGGAATGACAATAATTCCAGGCGTTCAGAGTGATCCTGACTGTACATCAAAAGAAAATTCGGGCCAGAGTAGCAGTTTAGCTAATGGTAAATTACGCGAAGTGCTGAAACATGGTGGAGTTTACACGACTTATTCTGGTCATGGAGATCATAACCTCAATGCTTCAGGTGTGAATGTTACTTCCTTGACTGAAGAGAAAATACTAGATGATTGCAAGCCTTGTATATCGAAAGAACTCCCTTGTAATTCTCGTGGAACTGATGAACTTTCCAGAAATGATGAAGAGAAGATTACTTTACCTGGTAAGGAGCTAGAGGAACAGTTATACAGTTATGGGTTTGAATCAGATCGTGGTTATGATCTATCTAGAGTAATAAAGGAGCAAGTTGGCAAAAGAAATTTGTGCGATGACGGGAAGGTCCAAGGACCAGCTGCCGTTTTCACGGAAAGTAATGAGGTTGCACATCCTGAGTGTGGTGGTTCTGAAACTGAACAAAGGAACATTAATGTTCCATGCCATGTCCACTTTCATAATTCTAACCATGTGGAAGAAAAAGGGAGTCAACCTGCACTTCTTGGTTATACAGGTGAAACTGAAGGCCGGATAGTTCAGGATGGTGAAGGAACGTCAGGTGTCTCTACAGTGTCAGGCGGCATTGAAAACCCTGAAATAGTAGATAACAGTAGTCCAGTTTCACTCAAGGCAGAAATGTCTACTATTGACAATGATTCTCCTATGGAGTGCAGTGACGGTAGTCAGAGTCGAATTATAAACTTAACTCAGGTTAAATCTCCAGTTAAGGCACTAGATGCTTCAGGCAGCTTTGTGCCACCCCGAATGGAAAGAGATAGATTTCATGATTTCCCACTCGAACCGCGGGAATATACTTTCAGAGGGAGTGATGAATCCTGCAAATTCTCGCGTGAGAGGTACCATGGCAGAATTATGAGAAGCCCAAGGTTAAATTTCATACCTGACAGAAGGAGATTACCTGATAACACAGAAAGCAATCTGCATGACCAGGACACAAAAAAATTTGAGTTTGATAATCATGGAAACACTCGTCGGGGTGGTGCTTTTATGAGTAATTTTCAGAGAGGGAGACGGCCTGCAAATGATGGAGTTACACCATATGCTCACTCCTTTCCGAGAAGATCCCCTAGCTTTTCATATAATAGAGGACCAACAAATAAAGAGGATACATCTGCATTTCACGGATTTAGAGATGGTGAAAAATTCACAAGGGGATTACAATGCAACAACACAGAACCACTGTTTATGAATCACCAACGTCCATATCGAGGTCGGAGTGGTTTTGCTCGAGGACGAACAAAGTTTGTAAACAACCCCAAACGAGATTTTCCTGGATTTCGTTCACGATCTCCAGTTAGATCAAGAGAAAGATCAGATGGTTCATCCTCGTCTTTCAGGAATAGATCACAGGAAGAGTTCAGTGGGCATACAGACTTTTCTCATCGAAGATCACCCTCAGGTTACAAAGTGGAGAGGATGAGCTCGCCTGACCATTCTGGTTATTCAAGAGAAATGGTTGTCAGAAGACACAATTCTCCACCTTTCTCGCATAGACCATCGAATGCTGGAAGGGGCCGGGGTTATGCAAGGGGCCGAGGTTATGTAAGGGGTCGAGGTTATGGAAGAGATGGCAACTCATTTAGGAAACCATCTGATCATGTTGTACATAGAAACCATGGAAACATGAATAACTTGGATCCTCGAGAAAGGGTTGACTATAGTGATGATTTCTTTGAAGGTCAAATTCATTCTGAACGATTTGGTGTTGATGTTAATGCTGAGAGAAGACGATTTGGTTATAGACATGATGGTACCAGCAGCTCTTTTAGACCATCTTTTAACAATGATGGTTGTGCACCTACTAATGTAGAGAATGACCCTGATGCTGTGAGGTTCCAACAAGACCCTCGTATTAAAATTGAAGAACAAGGGAGTTTAATGGAAATTGATGGAGAAAATAAGAACTCAACTGAGAATGCATCTGGAAGAACTAAGAATATGGAAGAGGAAGAAACTTCAAAGAACAGTAAAATTTGGCAACCGGATGAGCTCGGTGGTGATGGTTTTTAA
>AT5G13590.2
ATGTCTGGAAGCCAAGAGCCTAGGATCAGACCATCTACATGGAGCTGCAGTGATATTCCAATCAAGAAGAGGAAGTACCTTGTTCAGCCGCAAATGGAAGAAGCTGTCTCCACTCAGATTCCACAACCTAATGAGCAAGGTGATACTAGGAGTGCTCATGCTGACGAAACTCAGAAAATGACTGGTCGAGAACCAACCTCTTCATTACCATCTGTTCCTGTGGGAATTTCTGGTAAAGGGAAGAGCATTGGGAACATAGTTTTTGACCAAACTAGAGTGAAATTTGAGAAGCCAAGTTCTCCAATTCACTCCAGTCCATTGGCAGGCTTTGACATCCCTTCTAGTTCTAACGTACTTGGCAGTTCAATCCATTTTCCTATGGGAAAGCTTCCTGTTGGTGCTGAACATGCTGGTCTTGTTGTCCCCTCAAATCAAACTCGGATGAAAGTAGAAAAAACTGTTCTTAAGACTCATGATATAGTCCGGAAGACAGGTGACAAGGAAACTCTCAGAGGAGAGTGTCAAACAGAAGCATCTTCTGGTGCTAAGACTGTTTCCTTACAGCTAAGTTGTAACACTAAAAACAATTCTCCATATTGGAAGAATGAAGAGCCTACAGAACTGAATTTGTCATTAAGCAAGGGAGTTTGTCCCGCTCATAACACAGATTCTACTTCTACCAAATCTGGCAACAGTGGCCTGAACAGAGAAAATTGGGATTTGAATACTACCATGGATGTTTGGGAAGATGCTCTAGATCGCACAAGTGGTGCATTCTTAAACAGTAACAGAAGTCTTCGTGACATAGAGAGATCAAGTTGTCGTGATACGACTGCTATTACAAAGTCTGTTTCTGAAAGACAGAAGGAAAGTGTAGGATTTAGTTCTCCTAAGGTGACGTTGATGCAGTTTGATAATCATGTTAATCCCACATGCTCACTTAGTCTAGGCCTCAGTTCATATCCTCCTATTGAGAAATCTCCTTCTCTACCAGCTACCACATCAGAGGCAAGAGCTGGGAATGTGTGTTCAGTGAACCTTAGGACTGTGAAGTCAGAAATCATTGAAGAGAGTGTTAGGCAGGCAACAGAGAGTACTCAAGTTTCTCCAATCGGGCTATCTATTAAAGGACTGAAACATGAGGGTATTGGCAGATTCAGCCAAGGAAATAGTCCCTCATTTGGCATTTTGAAGACAGTGGTTCCTATATCAATAAAGGCTGAGCCAAATACCTTCTCTCAATCAGAAGTTTTCAATAGGAAAGATGGAATGTTGAATCATCCCCATACCCCAATAATGCAATCAAATGAGATCCCTGATTTACCTACAAGTTCTACGCCATATCAGAAGGATAAATATTTACCTTGTTCAAATGGTATCAGCAATGCACCAATGCCCTTGAGTGGAATGACAATAATTCCAGGCGTTCAGAGTGATCCTGACTGTACATCAAAAGAAAATTCGGGCCAGAGTAGCAGTTTAGCTAATGGTAAATTACGCGAAGTGCTGAAACATGGTGGAGTTTACACGACTTATTCTGGTCATGGAGATCATAACCTCAATGCTTCAGGTGTGAATGTTACTTCCTTGACTGAAGAGAAAATACTAGATGATTGCAAGCCTTGTATATCGAAAGAACTCCCTTGTAATTCTCGTGGAACTGATGAACTTTCCAGAAATGATGAAGAGAAGATTACTTTACCTGGTAAGGAGCTAGAGGAACAGTTATACAGTTATGGGTTTGAATCAGATCGTGGTTATGATCTATCTAGAGTAATAAAGGAGCAAGTTGGCAAAAGAAATTTGTGCGATGACGGGAAGGTCCAAGGACCAGCTGCCGTTTTCACGGAAAGTAATGAGGTTGCACATCCTGAGTGTGGTGGTTCTGAAACTGAACAAAGGAACATTAATGTTCCATGCCATGTCCACTTTCATAATTCTAACCATGTGGAAGAAAAAGGGAGTCAACCTGCACTTCTTGGTTATACAGGTGAAACTGAAGGCCGGATAGTTCAGGATGGTGAAGGAACGTCAGGTGTCTCTACAGTGTCAGGCGGCATTGAAAACCCTGAAATAGTAGATAACAGTAGTCCAGTTTCACTCAAGGCAGAAATGTCTACTATTGACAATGATTCTCCTATGGAGTGCAGTGACGGTAGTCAGAGTCGAATTATAAACTTAACTCAGGTTAAATCTCCAGTTAAGGCACTAGATGCTTCAGGCAGCTTTGTGCCACCCCGAATGGAAAGAGATAGATTTCATGATTTCCCACTCGAACCGCGGGAATATACTTTCAGAGGGAGTGATGAATCCTGCAAATTCTCGCGTGAGAGGTACCATGGCAGAATTATGAGAAGCCCAAGGTTAAATTTCATACCTGACAGAAGGAGATTACCTGATAACACAGAAAGCAATCTGCATGACCAGGACACAAAAAAATTTGAGTTTGATAATCATGGAAACACTCGTCGGGGTGGTGCTTTTATGAGTAATTTTCAGAGAGGGAGACGGCCTGCAAATGATGGAGTTACACCATATGCTCACTCCTTTCCGAGAAGATCCCCTAGCTTTTCATATAATAGAGGACCAACAAATAAAGAGGATACATCTGCATTTCACGGATTTAGAGATGGTGAAAAATTCACAAGGGGATTACAATGCAACAACACAGAACCACTGTTTATGAATCACCAACGTCCATATCGAGGTCGGAGTGGTTTTGCTCGAGGACGAACAAAGTTTGTAAACAACCCCAAACGAGATTTTCCTGGATTTCGTTCACGATCTCCAGTTAGATCAAGAGAAAGATCAGATGGTTCATCCTCGTCTTTCAGGAATAGATCACAGGAAGAGTTCAGTGGGCATACAGACTTTTCTCATCGAAGATCACCCTCAGGTTACAAAGTGGAGAGGATGAGCTCGCCTGACCATTCTGGTTATTCAAGAGAAATGGTTGTCAGAAGACACAATTCTCCACCTTTCTCGCATAGACCATCGAATGCTGGAAGGGGCCGGGGTTATGCAAGGGGCCGAGGTTATGTAAGGGGTCGAGGTTATGGAAGAGATGGCAACTCATTTAGGAAACCATCTGATCATGTTGTACATAGAAACCATGGAAACATGAATAACTTGGATCCTCGAGAAAGGGTTGACTATAGTGATGATTTCTTTGAAGGTCAAATTCATTCTGAACGATTTGGTGTTGATGTTAATGCTGAGAGAAGACGATTTGGTTATAGACATGATGGTACCAGCAGCTCTTTTAGACCATCTTTTAACAATGATGGTTGTGCACCTACTAATGTAGAGAATGACCCTGATGCTGTGAGGTTCCAACAAGACCCTCGTATTAAAATTGAAGAACAAGGGAGTTTAATGGAAATTGATGGAGAAAATAAGAACTCAACTGAGAATGCATCTGGAAGAACTAAGAATATGGAAGAGGAAGAAACTTCAAAGAACAGTAAAATTTGGCAACCGGATGAGCTCGGTGGTGATGGTTTTTAA
>AT5G24230.3
ATGGAAGAAGAAGATGATGAGGTTATGGTCAGAGAGGGGCTAATGGCCTCTCAAAGAGAAATCTTCAGCATTTCTGGTCCAATCCATTTAACTTCCATTGATTGGAATAATTCTTATCATAGAACCTCGGTGGCATCATGTTTGGTACAAGCAGTGTACACATTGGAACGAGACAGACAACAAAACAGGATTGGCCTAAAGTCACAAGCCAATCATTGGTGGGAGTTTTTCAACTTCACTTTAGCCGAAACCCTAATCGACGACTCAGACGGATCTATATACGGCGCCGTTTTCGAATACAAACATTTCTTCTCCTACAATTACCATCACACCCCTCATTCGAAACCACCTCCTCGTCACGTGATTGCTTTCCGTGGCACGATCTTGAAACCGCACTCTCGGTCACGTGACCTTAAGCTCGACCTACGTTGCATCCGAGACTCTCTCCATGATAGCACTCGGTTCGTGCATGCCATTCAGGTTATTCAAAGTGCGGTGGCTAAAACTGGTAATGCAGCCGTGTGGCTCGCCGGACATTCTCTTGGAGCAGCCGTGGCTTTGCTTGCCGGGAAGATTATGACAAGGTCTGGTTTTCCTCTTGAGAGTTACTTATTCAATCCTCCTTTCTCGTCTATTCCGATAGAGAAGCTAGTGAAGAGTGAGAAGCTTAAACATGGGGTTCGATTCGCCGGAAGTCTTGTTAAAGCCGGAGTTGCCATCGCCGTTAAGGGTCGCCACCATAATAAGGGTCAAGAAGACGATTCGTTCATGAAGTTAGCATCATGGATACCATATTTGTATTTGAATCCGTTAGATACAATATGCTCAGAATACATTGGTTACTTCAAGCACAGAAACAAAATGTTTGAGATCGGAGCCGGTAAAATCGAAAGAATTGCTACGAGGAACTCACTTAGGAGTCTGTTGTCAGGAGGAGGAGGAGGAGGTTCATCTTCAGATTCTTCTTCAGAGCCTCTTCATCTTTTACCATCGGCATATATGACGATAAACGCTAGCAAATCGCCGAATTTTAAGAGAGCTCATGGGATTCATCAATGGTGGGATCCCATGTTTAATGGTGAATATGTTTTGCATCAGTTTAATAACTAA
```

command: `wgd -v debug  ksd small.mcl sample.fasta --wm phyml -o sample.out`

output: 
```
   AlignmentCoverage   AlignmentIdentity   AlignmentLength AlignmentLengthStripped Distance    Family  Ka  Ks  Node    Omega   Paralog1    Paralog2    WeightOutliersIncluded  WeightOutliersExcluded
AT5G13590.1__AT5G13590.2    1.0 1.0 3504.0  3504.0  0.0 GF_000008   0.0 0.0 2.0 0.001   AT5G13590.1 AT5G13590.2 1.0 0.0
AT4G30820.17__AT4G30820.27  0.89899 1.0 594.0   534.0   0.0 GF_000004   0.0 0.0 3.0 0.7471  AT4G30820.27    AT4G30820.17    1.0 0.0
AT4G30820.16__AT4G30820.27  0.85859 0.85098 594.0   510.0   0.56848 GF_000004   0.166   0.1886  4.0 0.8806  AT4G30820.16    AT4G30820.27    0.5 0.5
AT4G30820.16__AT4G30820.17  0.85859 0.85098 594.0   510.0   0.56848 GF_000004   0.166   0.1886  4.0 0.8806  AT4G30820.16    AT4G30820.17    0.5 0.5
AT3G53830.1__AT3G53830.3    0.89831 0.99057 1416.0  1272.0  0.03762 GF_000006   0.0084  0.0133  2.0 0.6279  AT3G53830.1 AT3G53830.3 1.0 1.0
AT4G14390.3__AT4G14390.4    0.74929 0.98859 2106.0  1578.0  0.01366 GF_000003   0.0123  0.0178  3.0 0.6919  AT4G14390.4 AT4G14390.3 1.0 1.0
AT4G03460.2__AT4G14390.4    0.83618 0.56104 2106.0  1761.0  1.78644 GF_000003   0.5649  1.5382  4.0 0.3673  AT4G03460.2 AT4G14390.4 0.5 0.5
AT4G03460.2__AT4G14390.3    0.64387 0.57153 2106.0  1356.0  1.7885  GF_000003   0.564   1.5322  4.0 0.3681  AT4G03460.2 AT4G14390.3 0.5 0.5
AT4G10955.1__AT5G24230.3    0.90237 0.577   1137.0  1026.0  1.10504 GF_000002   0.4267  2.1848  3.0 0.1953  AT5G24230.3 AT4G10955.1 1.0 1.0
AT5G24210.1__AT5G24230.3    0.91557 0.6196  1137.0  1041.0  1.31704 GF_000002   0.422   1.1156  4.0 0.3782  AT5G24210.1 AT5G24230.3 0.5 0.5
AT4G10955.1__AT5G24210.1    0.88127 0.48004 1137.0  1002.0  2.04701 GF_000002   0.6653  4.4183  4.0 0.1506  AT5G24210.1 AT4G10955.1 0.5 0.5
AT1G01080.3__AT5G53680.1    0.58537 0.38889 861.0   504.0   190.80654   GF_000005   0.9774  67.4603 2.0 0.0145  AT1G01080.3 AT5G53680.1 1.0 0.0
AT4G14710.5__AT4G14710.6    0.90547 1.0 603.0   546.0   0.0 GF_000007   0.0 0.0 2.0 0.3533  AT4G14710.5 AT4G14710.6 1.0 0.0
AT3G04980.3__AT5G09540.1    0.22556 0.44074 3591.0  810.0   1.76962 GF_000001   0.9333  62.1468 3.0 0.015   AT5G09540.1 AT3G04980.3 1.0 0.0
AT5G09540.1__AT5G50620.1    0.17544 0.3873  3591.0  630.0   2.56261 GF_000001   1.1107  64.2613 4.0 0.0173  AT5G50620.1 AT5G09540.1 0.5 0.0
AT3G04980.3__AT5G50620.1    0.18296 0.45053 3591.0  657.0   2.01953 GF_000001   0.8052  78.3899 4.0 0.0103  AT5G50620.1 AT3G04980.3 0.5 0.0
```

Can you verify if this works for you? 

Note: The ALC (average linkage clustering) is of course not necessary, but it's a small hack to get the results in the same data structure with no overhead

**Comment by BiodivGenomic** [comment] 2019-02-05 10:47
Hi,
I got an output, but shorter than what you showed...

[sample.fasta.ks.txt](https://github.com/arzwa/wgd/files/2831722/sample.fasta.ks.txt)

I continue to explore my issue, and it seems to be more related to families with 3 members, when one is filtered, resulting in 2 sequences to be treated by PhyML (and thus after the ALC filter to be applied)...

For example, below is the part of the debug concerning a family with 3 members :
[results_3genes_family.txt](https://github.com/arzwa/wgd/files/2831755/results_3genes_family.txt)

As I remember it was not this family that failed in the previous analysis (maybe the first step is not using exactly the same order each time ?), it seems difficult to just remove the problematic families...

**Comment by arzwa** [comment] 2019-02-05 10:56
Whoops, you are correct, my output was from a different test, I edited it. 

I see you are running the analysis with the `--pairwise` flag, that's not really necessary and I would suggest not using it (it's slower, and does not matter for the results, it's there for compatibility reasons with earlier analyses). I think the bug you found might be alleviated when using the family-wise approach (without specfying the `--pairwise` flag).  Can you test whether it works without the `--pairwise` flag?

**Comment by BiodivGenomic** [comment] 2019-02-05 12:11
OK, I'm testing without the --pairwise flag.

**Comment by BiodivGenomic** [comment] 2019-02-07 19:14
Hi, the --pariwise flag doesn't seem to solve the issue...
I ran the ksd step using different genomes, with different characteristics (number of genes, the way the genes are named, etc), and the 3 are stalled, each at a family with 3 genes (using multiprocessing, thus maybe the same than in the other issue apply...). Two are on my computer, the third one is on a distant cluster, thus I don't think it's computer-specific. The 3 are stalled ot the phyml step ("DEBUG	Running PhyML: phyml -i ..."). the analysis is going faster with the reading of the mcl file (make sense, as the families are smaller and smaller), thus I don't think it's "normal" to have the phyml step for a family running for more than 2 days...

**Comment by arzwa** [comment] 2019-02-08 07:47
No that definitely does not sound good, and I haven't have these problems before myself. I will need some small example data set to try to reproduce this issue and do he debugging. Could you provide me a small set of families + sequences where you have this issue? Thanks

**Comment by BiodivGenomic** [comment] 2019-02-08 10:25
I checked the analyses that is running on my computer, and the last family entirely treated (with a fasta, fasta.msa and .ks files) is the last family with 3 members in the mcl file.
Also, I'm running them now using fasttree instead of phyml, and the first one completed...

**Comment by arzwa** [comment] 2019-02-27 09:50
Hi, may I ask if you still have issues related to the above? If not I'd like to close this, if you do have issues I'd like to solve them.

**Comment by arzwa** [comment] 2019-07-17 07:22
closed due to no follow-up

**Closed by arzwa** 2019-07-17 07:22 UTC
